name: nas_shutdown_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  #Network
  dartssh2: ^2.7.3
  web_socket_channel: ^2.1.0

  #Architecture
  bloc: ^8.1.0

  #Data
  freezed_annotation:  ^2.2.0
  json_annotation: ^4.7.0

  #Tools
  encrypt: ^5.0.1
  rxdart: ^0.27.5

  iot_models:
    git:
      url: https://github.com/NikitaMasev/iot_models.git
      ref: main

dev_dependencies:
  freezed: ^2.3.0
  lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2