name: nas_shutdown_client
description: A iot client for tracking battery voltage of nas.It allow to shutdown nas remotely.
version: 1.1.5
publish_to: none

environment:
  sdk: '>=3.0.0 <3.5.0'

dependencies:
  #Network
  dartssh2: ^2.8.2

  #Tools
  rxdart: ^0.27.7

  #Monitoring
  sentry: ^7.10.1

  iot_client_starter:
    git:
      url: https://github.com/NikitaMasev/iot_client_starter.git
      ref: main

dev_dependencies:
  lints: ^2.1.1