name: nas_shutdown_client
description: A sample command-line application.
version: 1.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <3.5.0'

dependencies:
  #Network
  dartssh2: ^2.7.3

  #Tools
  rxdart: ^0.27.5

  iot_client_starter:
    git:
      url: https://github.com/NikitaMasev/iot_client_starter.git
      ref: main

dev_dependencies:
  freezed: ^2.3.0
  lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2